language: node_js
sudo: false
node_js:
  - stable
addons:
  firefox: '42.0'

before_script:
  - npm install web-component-tester
  - npm install bower
  - bower install
  - npm install polylint
  - polylint

script: xvfb-run wct
